name: Daily Update

on:
  schedule:
    - cron: '0 8,20 * * *'  # Runs twice a day at 8 AM and 8 PM UTC
  workflow_dispatch:  # Allows for manual triggering

jobs:
  update_dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run create_controls_db.py
        run: python scripts/create_controls_db.py

      - name: Run generate_graphs.py
        run: python scripts/generate_graphs.py

      - name: Run update_dashboard.py
        run: python scripts/update_dashboard.py
