name: Daily Update

on:
  schedule:
    - cron: '0 13,1 * * *'  # 8 AM & 8 PM EST in UTC
  workflow_dispatch:

jobs:
  update_dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create SQLite database
        run: python scripts/create_controls_db.py

      - name: Generate graphs
        run: python scripts/generate_graphs.py

      - name: Generate badges
        run: python scripts/generate_badges.py

      - name: Update dashboard
        run: python scripts/update_dashboard.py
